CREATE TABLE alert_incident (
    incident_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fingerprint VARCHAR(200) NOT NULL,
    status VARCHAR(20) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    owner VARCHAR(100) NOT NULL,
    team VARCHAR(100) NOT NULL,
    service_name VARCHAR(100),
    service_version VARCHAR(100),
    error_code VARCHAR(100),
    http_method VARCHAR(10),
    uri_template VARCHAR(255),
    alert_name VARCHAR(255),
    summary TEXT,
    alert_message TEXT,
    grafana_alert_url TEXT,
    runbook_url TEXT,
    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    event_count INTEGER NOT NULL DEFAULT 1,
    last_notified_at TIMESTAMP,
    ack_by VARCHAR(100),
    ack_comment TEXT,
    ack_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_alert_incident PRIMARY KEY (incident_id),
    CONSTRAINT uk_alert_incident_fingerprint UNIQUE (fingerprint)
);

CREATE INDEX idx_alert_incident_status ON alert_incident(status);
CREATE INDEX idx_alert_incident_owner_status ON alert_incident(owner, status);