-- 1. 28번 요금제에 가입된 회원의 구독 내역 먼저 지움
DELETE FROM subscription WHERE product_id = 28;

-- 2. 이제 아무도 이 요금제를 안 쓰므로, 상품 기본 정보를 안전하게 지움
DELETE FROM product WHERE product_id = 28;

-- 가족 결합 내 역할 ENUM (대표자, 일반 구성원)
CREATE TYPE family_role_type AS ENUM ('REPRESENTATIVE', 'MEMBER');

-- 가족 결합 테이블 생성
CREATE TABLE family_group (
    family_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_family_group PRIMARY KEY (family_group_id)
);

-- 기존 회원 (Member) 테이블 수정 (자식 수, 가족 결합 FK 추가)
ALTER TABLE member
    -- 자식 수 (기본값 0)
    ADD COLUMN children_count INTEGER NOT NULL DEFAULT 0,

    -- 가족 결합 그룹 ID (결합 안 한 사람도 있으므로 NULL 허용)
    ADD COLUMN family_group_id BIGINT,

    -- 결합 그룹 내 역할 (결합 안 한 사람은 NULL)
    ADD COLUMN family_role family_role_type;

-- 가족 결합 그룹 테이블과의 외래키(FK) 연결
-- (가족 그룹이 삭제되면 회원의 결합 정보만 NULL로 초기화되도록 ON DELETE SET NULL 설정)
ALTER TABLE member
    ADD CONSTRAINT fk_member_to_family_group
    FOREIGN KEY (family_group_id) REFERENCES family_group (family_group_id) ON DELETE SET NULL;

-- 미납/완납 테이블
CREATE TABLE billing (
    billing_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- 누구의 청구서인가? (회원 테이블 연결)
    member_id       BIGINT      NOT NULL,

    -- 청구 년월 (예: '202602')
    yyyymm          VARCHAR(6)  NOT NULL,

    -- 미납/완납 여부 (TRUE: 완납, FALSE: 미납)
    is_paid         BOOLEAN     NOT NULL,

    created_at      TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_billing PRIMARY KEY (billing_id),

    -- 회원이 탈퇴하면 청구 내역도 지워지도록 CASCADE 설정
    CONSTRAINT fk_billing_to_member FOREIGN KEY (member_id)
        REFERENCES member (member_id) ON DELETE CASCADE,

    -- 논리적 제약조건: 한 회원(member_id)은 같은 달(yyyymm)에 하나의 청구 상태만 가짐
    CONSTRAINT uk_billing_member_month UNIQUE (member_id, yyyymm)
);