-- ENUM 타입 정의
CREATE TYPE member_status_type AS ENUM ('ACTIVE', 'BANNED', 'DELETED', 'PROCESSING');
CREATE TYPE member_signup_type AS ENUM ('GOOGLE', 'KAKAO', 'NAVER', 'FORM');
CREATE TYPE member_role_type AS ENUM ('GUEST', 'COUNSELOR', 'CUSTOMER', 'ADMIN');
CREATE TYPE member_membership_type AS ENUM ('VVIP', 'VIP', 'GOLD', 'BASIC');

-- 주소 테이블
CREATE TABLE address (
    address_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,

    province       VARCHAR(50)  NOT NULL, -- 경기도
    city           VARCHAR(50)  NOT NULL, -- 성남시
    street_address VARCHAR(100) NOT NULL, -- 판교역로 123

    -- 우편번호는 Unique 조건에서 제외 (같은 건물도 우편번호 바뀔 수 있음)
    postal_code    VARCHAR(10)  NOT NULL,

    created_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_address PRIMARY KEY (address_id),

    -- "시 + 구 + 도로명"이 같으면 같은 주소로 취급 (중복 저장 방지)
    CONSTRAINT uk_address_unique UNIQUE (province, city, street_address)
);

-- 회원 테이블
CREATE TABLE member (
    member_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,

    address_id        BIGINT,

    -- 소셜 로그인용 고유 식별자
    provider_id       VARCHAR(100),

    email             VARCHAR(100) NOT NULL,

    -- 소셜 로그인은 비밀번호 없으므로 NULL 허용
    password          VARCHAR(100),

    name              VARCHAR(50)  NOT NULL,

    -- 조건부 정보 (NULL 허용)
    phone             VARCHAR(100),
    birth_date        DATE,
    gender            VARCHAR(1),

    -- 날짜 정보
    join_date         DATE         NOT NULL DEFAULT CURRENT_DATE,
    created_at        TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP    NOT NULL DEFAULT NOW(),
    status_updated_at TIMESTAMP    NOT NULL DEFAULT NOW(),

    -- ENUM 컬럼
    status            member_status_type     NOT NULL DEFAULT 'PROCESSING',
    type              member_signup_type     NOT NULL DEFAULT 'FORM',
    role              member_role_type       NOT NULL DEFAULT 'CUSTOMER',
    membership        member_membership_type,

    -- PK / UK / FK 설정
    CONSTRAINT pk_member PRIMARY KEY (member_id),
    CONSTRAINT uk_member_email UNIQUE (email),
    CONSTRAINT uk_member_phone UNIQUE (phone),
    CONSTRAINT fk_member_to_address FOREIGN KEY (address_id) REFERENCES address(address_id),

    -- 로그인 방식별 필수 데이터 체크
    -- FORM 가입은 비밀번호 필수, 소셜 가입은 provider_id 필수
    CONSTRAINT ck_auth_method CHECK (
        (type = 'FORM' AND password IS NOT NULL)
        OR
        (type <> 'FORM' AND provider_id IS NOT NULL)
    ),

    -- 고객(Customer) 필수 정보 체크
    CONSTRAINT ck_member_info_required CHECK (
        (role = 'CUSTOMER' AND phone IS NOT NULL
                           AND birth_date IS NOT NULL
                           AND gender IS NOT NULL
                           AND address_id IS NOT NULL
                           AND membership IS NOT NULL)
        OR (role <> 'CUSTOMER')
    )
);

-- 상품 타입 ENUM 정의
CREATE TYPE product_type_enum AS ENUM (
    'MOBILE_PLAN',     -- 5G/LTE 요금제
    'INTERNET',        -- 인터넷 요금제
    'IPTV',            -- TV 요금제
    'TAB_WATCH_PLAN',  -- 태블릿/스마트워치 요금제
    'ADDON'            -- 부가 서비스
);

-- 상품 테이블
CREATE TABLE product (
    product_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- 상품 식별 번호 (중복 불가)
    product_code   VARCHAR(50)  NOT NULL,

    -- 기본 정보
    name           VARCHAR(50)  NOT NULL,
    price          INTEGER      NOT NULL, -- 정상가
    sale_price     INTEGER      NOT NULL, -- 할인가 (할인 안 하면 price와 같은 값 넣기)

    -- ENUM 적용
    product_type   product_type_enum NOT NULL,

    -- 할인 종류 (NULL 허용)
    discount_type  VARCHAR(100),

    -- 생성일/수정일
    created_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP    NOT NULL DEFAULT NOW(),

    -- PK 및 제약조건 설정
    CONSTRAINT pk_product PRIMARY KEY (product_id),
    CONSTRAINT uk_product_code UNIQUE (product_code) -- 상품 코드는 유일해야 함
);

-- 5G/LTE 요금제 테이블
CREATE TABLE mobile_plan (
    product_id                        BIGINT       NOT NULL,

    data_amount                       VARCHAR(100) NOT NULL, -- 제공 데이터
    tethering_sharing_data            VARCHAR(100),          -- 테더링/쉐어링 (NULL 가능)
    benefit_sms                       VARCHAR(100) NOT NULL, -- 문자 혜택
    benefit_voice_call                VARCHAR(100) NOT NULL, -- 음성 혜택

    -- 제휴 혜택 관련 (NULL 가능)
    benefit_brands                    VARCHAR(100),          -- 혜택 제공 브랜드
    benefit_media                     VARCHAR(100),          -- 미디어 혜택
    benefit_premium                   VARCHAR(100),          -- 프리미엄 혜택
    benefit_signature_family_discount VARCHAR(100),          -- 시그니처 가족 할인

    created_at                        TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at                        TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_mobile_plan PRIMARY KEY (product_id),

    -- product 테이블이 지워지면 같이 지워지도록(CASCADE) 설정
    CONSTRAINT fk_mobile_plan_to_product FOREIGN KEY (product_id)
        REFERENCES product (product_id) ON DELETE CASCADE
);

-- 태블릿/스마트워치 요금제 테이블
CREATE TABLE tab_watch_plan (
    product_id          BIGINT       NOT NULL,

    -- 제공 데이터
    data_amount         VARCHAR(100) NOT NULL,

    -- 음성/문자는 없는 요금제도 있으므로 NULL 허용
    benefit_voice_call  VARCHAR(100),
    benefit_sms         VARCHAR(100),

    created_at          TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_tab_watch_plan PRIMARY KEY (product_id),

    CONSTRAINT fk_tab_watch_plan_to_product FOREIGN KEY (product_id)
        REFERENCES product (product_id) ON DELETE CASCADE
);

-- IPTV 요금제 테이블
CREATE TABLE iptv (
    product_id     BIGINT       NOT NULL,
    plan_title     VARCHAR(100) NOT NULL,
    channel        INTEGER      NOT NULL,
    benefits       VARCHAR(100) NOT NULL,

    created_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_iptv PRIMARY KEY (product_id),

    CONSTRAINT fk_iptv_to_product FOREIGN KEY (product_id)
        REFERENCES product (product_id) ON DELETE CASCADE
);

-- 인터넷 요금제 테이블
CREATE TABLE internet (
    product_id  BIGINT       NOT NULL,
    plan_title  VARCHAR(100) NOT NULL,
    speed       VARCHAR(50)  NOT NULL,
    benefits    VARCHAR(255) NOT NULL,

    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_internet PRIMARY KEY (product_id),

    CONSTRAINT fk_internet_to_product FOREIGN KEY (product_id)
        REFERENCES product (product_id) ON DELETE CASCADE
);

-- 부가서비스 타입 ENUM 정의
CREATE TYPE addon_type_enum AS ENUM (
    'FAMILY_CARE',    -- 가족케어
    'PHONE_CARE',     -- 휴대폰케어
    'DIGITAL'         -- 디지털콘텐츠
);

-- 부가 서비스 상세 테이블
CREATE TABLE addon_service (
    product_id  BIGINT           NOT NULL,
    addon_type  addon_type_enum  NOT NULL,
    description VARCHAR(500)     NOT NULL,

    created_at  TIMESTAMP        NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP        NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_addon_service PRIMARY KEY (product_id),

    CONSTRAINT fk_addon_service_to_product FOREIGN KEY (product_id)
        REFERENCES product (product_id) ON DELETE CASCADE
);

-- 구독 테이블
CREATE TABLE subscription (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    member_id       BIGINT      NOT NULL,
    product_id      BIGINT      NOT NULL,

    start_date      TIMESTAMP   NOT NULL DEFAULT NOW(), -- 구독 시작일
    end_date        TIMESTAMP,                          -- 실제 해지일 (구독 중이면 NULL, 해지 시 시점 기록)

    -- TRUE: 구독중, FALSE: 해지됨
    status          BOOLEAN     NOT NULL DEFAULT TRUE,

    created_at      TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_subscription PRIMARY KEY (subscription_id),

    CONSTRAINT fk_subscription_to_member FOREIGN KEY (member_id)
        REFERENCES member(member_id),

    CONSTRAINT fk_subscription_to_product FOREIGN KEY (product_id)
        REFERENCES product(product_id)
);

-- 월별 사용량 테이블
CREATE TABLE usage_monthly (
    usage_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subscription_id BIGINT      NOT NULL,

    -- 사용 년월 (ex: '202602')
    yyyymm          VARCHAR(6)  NOT NULL,

    -- 상세 사용량 데이터 (PostgreSQL 전용 JSONB 타입)
    -- 데이터, 음성, 문자 등 구조화된 데이터를 유연하게 저장
    usage_details   JSONB       NOT NULL,

    created_at      TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_usage_monthly PRIMARY KEY (usage_id),

    CONSTRAINT fk_usage_monthly_to_subscription FOREIGN KEY (subscription_id)
        REFERENCES subscription (subscription_id) ON DELETE CASCADE
);

-- 최근 본 상품 테이블
CREATE TABLE product_view_history (
    view_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id    BIGINT      NOT NULL,
    product_id   BIGINT      NOT NULL,
    viewed_at    TIMESTAMP   NOT NULL DEFAULT NOW(),

    created_at   TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_product_view_history PRIMARY KEY (view_id),

    CONSTRAINT fk_product_view_history_to_member FOREIGN KEY (member_id)
        REFERENCES member (member_id) ON DELETE CASCADE,

    CONSTRAINT fk_product_view_history_to_product FOREIGN KEY (product_id)
        REFERENCES product (product_id) ON DELETE CASCADE
);

-- 쿠폰 유형 ENUM 정의
CREATE TYPE coupon_type_enum AS ENUM (
    'DISCOUNT', -- 가격 할인
    'DATA'      -- 데이터 제공
);

-- 쿠폰 테이블
CREATE TABLE coupon (
    coupon_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(100) NOT NULL,
    coupon_type     coupon_type_enum NOT NULL,

    -- 혜택 값 (ex: '10%', '10000원', '2GB' 등)
    benefit_value   VARCHAR(50)  NOT NULL,

    -- 쿠폰 상세설명
    description     VARCHAR(100) NOT NULL,

    -- 유효기간 종료일 (고정 기간용)
    valid_end_date  TIMESTAMP,

    -- 유효 기간 (발급 후 유지 일수, 동적 기간용)
    valid_days      INTEGER,

    created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_coupon PRIMARY KEY (coupon_id)
);

-- 회원 보유 쿠폰 테이블
CREATE TABLE member_coupon (
    member_coupon_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id        BIGINT      NOT NULL,
    coupon_id        BIGINT      NOT NULL,

    -- 사용 여부 (TRUE: 사용함, FALSE: 미사용)
    is_used          BOOLEAN     NOT NULL DEFAULT FALSE,

    -- 사용 날짜 (미사용 시 NULL)
    used_at          TIMESTAMP,

    -- 발급 받은 날짜
    issued_at        TIMESTAMP   NOT NULL DEFAULT NOW(),

    -- 만료 날짜 (해당 시점이 지나면 사용 불가)
    expired_at       TIMESTAMP   NOT NULL,

    created_at       TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_member_coupon PRIMARY KEY (member_coupon_id),

    CONSTRAINT fk_member_coupon_to_member FOREIGN KEY (member_id)
        REFERENCES member (member_id) ON DELETE CASCADE,

    CONSTRAINT fk_member_coupon_to_coupon FOREIGN KEY (coupon_id)
        REFERENCES coupon (coupon_id) ON DELETE CASCADE
);