-- ==========================================
-- 1. 신규 페르소나 타입 마스터 테이블 생성
-- ==========================================
CREATE TABLE IF NOT EXISTS persona_type (
    persona_type_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_name        VARCHAR(100) NOT NULL,
    short_desc            TEXT,
    character_description TEXT,
    version               INTEGER NOT NULL DEFAULT 1,
    is_active             BOOLEAN NOT NULL DEFAULT TRUE,
    tags                  TEXT[] NOT NULL DEFAULT '{}',
    created_at            TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_persona_type_name_version UNIQUE (character_name, version)
);

CREATE INDEX IF NOT EXISTS idx_persona_type_active_version
    ON persona_type (is_active, version DESC);

CREATE INDEX IF NOT EXISTS idx_persona_type_name
    ON persona_type (character_name);


-- ==========================================
-- 2. 기존 페르소나 스냅샷 테이블 변경 (V21에서 생성된 테이블에 컬럼 추가)
-- ==========================================
-- 2-1. persona_type_id 컬럼 추가
ALTER TABLE index_persona_snapshot
    ADD COLUMN persona_type_id BIGINT NOT NULL;

-- 2-2. 외래키(FK) 제약조건 추가
ALTER TABLE index_persona_snapshot
    ADD CONSTRAINT fk_index_persona_snapshot_persona_type
    FOREIGN KEY (persona_type_id) REFERENCES persona_type(persona_type_id);

-- 2-3. 조인을 위한 신규 인덱스 추가
CREATE INDEX IF NOT EXISTS idx_index_persona_snapshot_persona_type_id
    ON index_persona_snapshot (persona_type_id);