-- 이탈 위험도 스냅샷 (이탈 상세 점수의 부모, 1:1)
CREATE TABLE churn_score_snapshot (
    snapshot_id   BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    member_id     BIGINT  NOT NULL,
    churn_score   INTEGER NOT NULL,
    risk_level    VARCHAR(20) NOT NULL DEFAULT 'LOW'
        CHECK (risk_level IN ('HIGH', 'MEDIUM', 'LOW')),
    risk_reasons  JSONB   NOT NULL DEFAULT '[]'::jsonb,
    base_date     DATE    NOT NULL,

    CONSTRAINT pk_churn_score_snapshot PRIMARY KEY (snapshot_id),
    CONSTRAINT uq_churn_score_snapshot_member_date UNIQUE (member_id, base_date),
    CONSTRAINT fk_churn_score_snapshot_member
        FOREIGN KEY (member_id) REFERENCES member (member_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_churn_score_snapshot_base_date ON churn_score_snapshot (base_date);

COMMENT ON TABLE churn_score_snapshot IS '이탈 위험도 스냅샷 (회원·기준일별)';
COMMENT ON COLUMN churn_score_snapshot.churn_score IS '이탈 확률 점수';
COMMENT ON COLUMN churn_score_snapshot.risk_level IS '이탈 위험 등급 (HIGH/MEDIUM/LOW)';
COMMENT ON COLUMN churn_score_snapshot.risk_reasons IS '위험 사유 목록 (JSON 배열)';
COMMENT ON COLUMN churn_score_snapshot.base_date IS '스냅샷 기준일';

-- V27 테이블 컬럼 기본값 보강: contract_feature.tenure_weeks, usage_feature.allowance_usage_rate_pct
ALTER TABLE contract_feature
    ALTER COLUMN tenure_weeks SET DEFAULT 0;

ALTER TABLE usage_feature
    ALTER COLUMN allowance_usage_rate_pct SET DEFAULT 0;
