-- 이탈 위험도 스냅샷 (이탈 상세 점수의 부모, 1:1)
CREATE TABLE churn_score_snapshot (
    snapshot_id   BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    member_id     BIGINT  NOT NULL,
    churn_score   INTEGER NOT NULL,
    risk_level    VARCHAR(20) NOT NULL DEFAULT 'MEDIUM'
        CHECK (risk_level IN ('HIGH', 'MEDIUM', 'LOW')),
    risk_reasons  JSONB   NOT NULL DEFAULT '[]'::jsonb,
    base_date     DATE    NOT NULL,

    CONSTRAINT pk_churn_score_snapshot PRIMARY KEY (snapshot_id),
    CONSTRAINT fk_churn_score_snapshot_member
        FOREIGN KEY (member_id) REFERENCES member (member_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_churn_score_snapshot_member ON churn_score_snapshot (member_id);
CREATE INDEX idx_churn_score_snapshot_base_date ON churn_score_snapshot (base_date);

COMMENT ON TABLE churn_score_snapshot IS '이탈 위험도 스냅샷 (회원·기준일별)';
COMMENT ON COLUMN churn_score_snapshot.churn_score IS '이탈 확률 점수';
COMMENT ON COLUMN churn_score_snapshot.risk_level IS '이탈 위험 등급 (HIGH/MEDIUM/LOW)';
COMMENT ON COLUMN churn_score_snapshot.risk_reasons IS '위험 사유 목록 (JSON 배열)';
COMMENT ON COLUMN churn_score_snapshot.base_date IS '스냅샷 기준일';

-- 이탈 상세 점수 (스냅샷당 1행, 세부 점수 분해)
CREATE TABLE churn_feature_score (
    snapshot_id         BIGINT    NOT NULL,
    churn_base_score    SMALLINT,
    churn_usage_score   SMALLINT,
    churn_counsel_score SMALLINT,
    churn_log_score     SMALLINT,

    CONSTRAINT pk_churn_feature_score PRIMARY KEY (snapshot_id),
    CONSTRAINT fk_churn_feature_score_snapshot
        FOREIGN KEY (snapshot_id) REFERENCES churn_score_snapshot (snapshot_id)
        ON DELETE CASCADE
);

COMMENT ON TABLE churn_feature_score IS '이탈 상세 점수 (기본/사용량/상담/로그)';
COMMENT ON COLUMN churn_feature_score.churn_base_score IS '기본 배치 이탈 점수 (가중치 변경 가능)';
COMMENT ON COLUMN churn_feature_score.churn_usage_score IS '데이터 사용량 이탈 점수';
COMMENT ON COLUMN churn_feature_score.churn_counsel_score IS '상담 이탈 점수';
COMMENT ON COLUMN churn_feature_score.churn_log_score IS '로그 이탈 점수';
