CREATE TABLE refresh_token (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id        BIGINT NOT NULL,                             -- 소유 회원 ID
    token_hash       VARCHAR(128) NOT NULL,                       -- 토큰 해시
    revoked          BOOLEAN NOT NULL DEFAULT FALSE,              -- 폐기 여부

    expires_at       TIMESTAMPTZ NOT NULL,                        -- 만료 시각
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),          -- 생성 시각
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),          -- 수정 시각

    -- UK 토큰 해시값은 중복될 수 없음
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash),

    CONSTRAINT fk_refresh_token_member
        FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE CASCADE
);

-- [인덱스] 엔티티의 @Index 반영
-- 1. 특정 회원의 토큰 목록 조회 성능 향상 (로그아웃, 재발급 시 사용)
CREATE INDEX idx_refresh_token_member_id ON refresh_token (member_id);

-- 2. 만료된 토큰 일괄 삭제 배치 작업 성능 향상
CREATE INDEX idx_refresh_token_expires_at ON refresh_token (expires_at);