-- 상담 처리 상태 ENUM
CREATE TYPE support_status AS ENUM ('OPEN', 'SUPPORTING', 'CLOSED');

-- [1] 상담 카테고리(대분류) 마스터 테이블
CREATE TABLE category_group (
    category_group_code VARCHAR(20) NOT NULL,       -- 예: CG_MOB
    category_name VARCHAR(50) NOT NULL,      -- 예: 모바일

    CONSTRAINT pk_category_group PRIMARY KEY (category_group_code),
    CONSTRAINT uk_category_group_category_name UNIQUE (category_name)
);

-- [2] 상담 카테고리(소분류) 마스터 테이블
CREATE TABLE category (
    category_code VARCHAR(20) NOT NULL,             -- 예: MOB_001
    category_group_code VARCHAR(20) NOT NULL,       -- 카테고리 대분류 코드 FK
    category_name VARCHAR(50) NOT NULL,             -- 예: 가입/해지

    CONSTRAINT pk_category PRIMARY KEY (category_code),
    CONSTRAINT fk_category_to_group FOREIGN KEY (category_group_code) REFERENCES category_group(category_group_code) ON DELETE CASCADE
);

-- [3] 상담 테이블
CREATE TABLE support_case (
    case_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,                      -- 문의 작성 고객 PK
    counselor_id BIGINT,                            -- 상담사 PK
    category_code VARCHAR(20) NOT NULL,             -- 카테고리 소분류 코드 PK

    status support_status NOT NULL DEFAULT 'OPEN',  -- 처리 상태
    title VARCHAR(100) NOT NULL,                    -- 문의 제목
    question_text TEXT NOT NULL,                    -- 고객 질문 글
    answer_text TEXT,                               -- 상담사 답변 글
    satisfaction_score INTEGER,                     -- 만족도 점수

    -- 날짜/시간 정보
    customer_modified_at TIMESTAMP,                 -- 고객이 글 수정한 시간
    support_started_at TIMESTAMP,                   -- 상담사 답변 시작 시간
    resolved_at TIMESTAMP,                          -- 상담사 답변 종료 시간
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),    -- 고객이 글 올린 시간
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_support_case PRIMARY KEY (case_id),

    -- CHECK 제약 조건: 만족도는 0~5점 사이만 허용
    CONSTRAINT ck_support_case_score CHECK (satisfaction_score >= 0 AND satisfaction_score <= 5),

    -- FK
    CONSTRAINT fk_support_case_to_member FOREIGN KEY (member_id) REFERENCES member(member_id),
    CONSTRAINT fk_support_case_to_counselor FOREIGN KEY (counselor_id) REFERENCES member(member_id),
    CONSTRAINT fk_support_case_to_category FOREIGN KEY (category_code) REFERENCES category(category_code)
);

-- ==========================================
-- 마스터 데이터 초기 적재 (INSERT)
-- ==========================================

-- [1] 대분류 데이터 적재
INSERT INTO category_group (category_group_code, category_name) VALUES
('CG_MOB', '모바일'),
('CG_HOM', '홈 상품(인터넷/TV/스마트홈)'),
('CG_INT', '국제전화/부가전화'),
('CG_WEB', '홈페이지'),
('CG_MEM', '멤버십'),
('CG_PRV', '개인정보보호침해신고');

-- [2] 소분류 데이터 적재
-- 1. 모바일 하위 (MOB_xxx)
INSERT INTO category (category_code, category_group_code, category_name) VALUES
('MOB_001', 'CG_MOB', '가입/해지'),
('MOB_002', 'CG_MOB', '요금 조회/납부'),
('MOB_003', 'CG_MOB', '요금제/부가서비스'),
('MOB_004', 'CG_MOB', '결합상품'),
('MOB_005', 'CG_MOB', '휴대폰결제'),
('MOB_006', 'CG_MOB', '일시정지'),
('MOB_007', 'CG_MOB', '해외로밍'),
('MOB_008', 'CG_MOB', '통화품질'),
('MOB_009', 'CG_MOB', '육아 지원 데이터 혜택 신청');

-- 2. 홈 상품 하위 (HOM_xxx)
INSERT INTO category (category_code, category_group_code, category_name) VALUES
('HOM_001', 'CG_HOM', '가입/해지'),
('HOM_002', 'CG_HOM', '요금 조회/납부'),
('HOM_003', 'CG_HOM', '요금제/부가서비스'),
('HOM_004', 'CG_HOM', '결합상품'),
('HOM_005', 'CG_HOM', '설치장소 변경'),
('HOM_006', 'CG_HOM', '일시정지'),
('HOM_007', 'CG_HOM', '장애점검');

-- 3. 국제전화/부가전화 하위 (INT_xxx)
INSERT INTO category (category_code, category_group_code, category_name) VALUES
('INT_001', 'CG_INT', '국제전화 002'),
('INT_002', 'CG_INT', '수신자부담전화'),
('INT_003', 'CG_INT', '선불카드'),
('INT_004', 'CG_INT', '후불카드');

-- 4. 홈페이지 하위 (WEB_xxx)
INSERT INTO category (category_code, category_group_code, category_name) VALUES
('WEB_001', 'CG_WEB', '회원가입 및 로그인');

-- 5. 멤버십 하위 (MEM_xxx)
INSERT INTO category (category_code, category_group_code, category_name) VALUES
('MEM_001', 'CG_MEM', 'VIP콕 문의'),
('MEM_002', 'CG_MEM', '영화예매 문의'),
('MEM_003', 'CG_MEM', '유플투쁠 문의'),
('MEM_004', 'CG_MEM', '멤버십 등급 문의'),
('MEM_005', 'CG_MEM', '제휴사 혜택 문의'),
('MEM_006', 'CG_MEM', '멤버십 바코드 문의'),
('MEM_007', 'CG_MEM', '앱 기능 개선 요청');

-- 6. 개인정보보호침해신고 하위 (PRV_xxx)
INSERT INTO category (category_code, category_group_code, category_name) VALUES
('PRV_001', 'CG_PRV', '명의도용'),
('PRV_002', 'CG_PRV', '명의도용 외');