-- 상담 분석 상태 ENUM 정의
-- READY: 분석 대기 / IN_PROGRESS: 분석 중 / COMPLETED: 분석 성공 / FAILED: 분석 실패
CREATE TYPE analysis_status AS ENUM ('READY', 'IN_PROGRESS', 'COMPLETED', 'FAILED');

-- 비즈니스 키워드 마스터 테이블 (business_keyword)
CREATE TABLE business_keyword (
    business_keyword_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    keyword_code VARCHAR(10) NOT NULL,              -- 예: BK_MOB
    keyword_name VARCHAR(20) NOT NULL,              -- 예: 모바일
    is_active BOOLEAN NOT NULL DEFAULT false,       -- 키워드 사용 상태

    created_at TIMESTAMP NOT NULL DEFAULT NOW(),    -- 생성 날짜
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),    -- 수정 날짜

    CONSTRAINT pk_business_keyword PRIMARY KEY (business_keyword_id),
    CONSTRAINT uk_business_keyword_code UNIQUE (keyword_code)
);

-- 비즈니스 키워드 별칭 테이블 (business_keyword_alias)
CREATE TABLE business_keyword_alias (
    alias_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    business_keyword_id BIGINT NOT NULL,            -- 비즈니스 키워드 FK
    alias_text VARCHAR(100) NOT NULL,               -- 원문 별칭 (예: U+tv, 스마트 홈)
    alias_norm VARCHAR(100) NOT NULL,               -- 정규화 결과 (예: utv, 스마트홈)
    is_active BOOLEAN NOT NULL DEFAULT false,       -- 별칭 사용 상태

    created_at TIMESTAMP NOT NULL DEFAULT NOW(),    -- 생성 날짜
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),    -- 수정 날짜

    CONSTRAINT pk_business_keyword_alias PRIMARY KEY (alias_id),
    CONSTRAINT fk_alias_to_keyword FOREIGN KEY (business_keyword_id) REFERENCES business_keyword(business_keyword_id) ON DELETE CASCADE
);

-- 상담 분석 내역 테이블 (consultation_analysis)
CREATE TABLE consultation_analysis (
    analysis_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    case_id BIGINT NOT NULL,                        -- 기존 support_case(상담 티켓) FK
    job_instance_id BIGINT NOT NULL,                -- 스프링 배치 Job ID (추적용)
    analyzer_version BIGINT NOT NULL,               -- 분석기 버전

    analysis_status analysis_status NOT NULL DEFAULT 'READY', -- 분석 상태
    error_message TEXT,                             -- 분석 실패 시 에러 메시지
    processed_at TIMESTAMP,                         -- 분석 처리가 완료/실패된 최종 시간

    CONSTRAINT pk_consultation_analysis PRIMARY KEY (analysis_id),
    CONSTRAINT fk_analysis_to_case FOREIGN KEY (case_id) REFERENCES support_case(case_id) ON DELETE CASCADE
);

-- 비즈니스 키워드 매핑 결과 테이블 (business_keyword_mapping_result)
CREATE TABLE business_keyword_mapping_result (
    mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    analysis_id BIGINT NOT NULL,                    -- 상담 분석 내역 FK
    business_keyword_id BIGINT NOT NULL,            -- 추출된 비즈니스 키워드 FK

    count INTEGER NOT NULL DEFAULT 1,               -- 해당 티켓에서 키워드가 등장한 횟수
    change_rate DECIMAL(10, 2) NOT NULL DEFAULT 0.00, -- 이전 대비 증감율

    CONSTRAINT pk_mapping_result PRIMARY KEY (mapping_id),
    CONSTRAINT fk_mapping_to_analysis FOREIGN KEY (analysis_id) REFERENCES consultation_analysis(analysis_id) ON DELETE CASCADE,
    CONSTRAINT fk_mapping_to_keyword FOREIGN KEY (business_keyword_id) REFERENCES business_keyword(business_keyword_id) ON DELETE CASCADE
);